# Generated by Django 4.1.7 on 2023-02-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_for',
            new_name='article_for',
        ),
    ]
