# Generated by Django 4.1.7 on 2023-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(upload_to='post_banners/%Y/%m/%d/'),
        ),
    ]
